feat: Check tests for multiple Java SDK versions (#4)
* feat: Remove failing test

* feat: Parallel test execution

* feat: Update path to composite action

diff --git a/.github/workflows/run-tests-every-push.yml b/.github/workflows/run-tests-every-push.yml
--- a/.github/workflows/run-tests-every-push.yml
+++ b/.github/workflows/run-tests-every-push.yml
@@ -7,19 +7,69 @@ on:
       - main
 
 jobs:
-  build-and-test:
+  build-project:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Java SDK
+      - name: Setup Java SDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
 
-      - name: Run Maven build and build Unit tests
-        run: mvn --batch-mode clean test
+  prepare-tests:
+    runs-on: ubuntu-latest
+    name: Separate test files
+    needs: build-project
+
+    outputs:
+      test-classes: ${{ steps.split-tests.outputs.test-classes }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Split test classes
+        id: split-tests
+        uses: ./run-parallel-tests
+        with:
+          number-test-chunks: 2
+
+
+  run-tests:
+    runs-on: ubuntu-latest
+    name: Run test files in parallel
+    needs: prepare-tests
+    strategy:
+      matrix:
+        test-class: ${{ fromJson(needs.prepare-tests.outputs.test-classes) }}
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Run ${{ matrix.test-class }}
+        run: mvn test -Dtest=${{ matrix.test-class }}
+
+  test-summary:
+    runs-on: ubuntu-latest
+    # This job must run even if the matrix jobs fail, to report the failure
+    if: always()
+    needs: run-tests
+
+    steps:
+      - name: Report overall test status
+        run: |
+          # The 'needs' context contains the result of the dependent jobs.
+          # It will be 'success' only if ALL matrix jobs succeeded.
+          if [[ "${{ needs.run-tests.result }}" == "success" ]]; then
+            echo "✅ All build and test jobs passed."
+          else
+            echo "❌ One or more build and test jobs failed."
+            exit 1
+          fi
